### ISSUE TITLE
Have any documents about how to use this toolbox?

### ISSUE THREAD

**Issue by eliteyz** [PrincetonUniversity/3D3A-MATLAB-Toolbox#1]
Like the topic saying, I can find any reliable documents about this toolbox, so it might cause some trouble when I try to use it. Could please send me some of them? I would appreiate it, thanks.

**Comment by srahulram** [comment]
Hi,

We are working on putting together documentation but it may be a while before we publish it. Sorry about that. However, to use the toolbox, all you have to do is to navigate (from within MATLAB) to the toolbox's parent folder (containing the file "start3D3AMATLABToolbox.m") and run `start3D3AMATLABToolbox` in the Command Window to initialize the toolbox. This should add all the necessary folders to the MATLAB search path and, if you are connected to the internet, also download the dependencies. You can also install (i.e., download and add to the MATLAB search path) the dependencies manually. For more information on the required dependencies, please refer to the README file in the dependencies folder.

Once the toolbox is initialized, you can use the functions in the toolbox like you use any other MATLAB functions. Most functions have usage documentation which you can access by typing `help <function_name>` in the Command Window.

Please also note that some functions require additional MathWorks toolboxes such as the Signal Processing toolbox. So some functions may not work without a full installation of MATLAB R2018a or later. Finally, please also keep in mind that the toolbox is in its "alpha" (possibly very early "beta") stage of development.

Thanks.

**Comment by eliteyz** [comment]
Thanks for your reply.
It will be helpful.
